server:
  port: 8080

spring:
  datasource:
    url: ${LC_DB_URL}
    username: ${LC_DB_USERNAME}
    password: ${LC_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: ${PRAGMA_JWT_KEY}
      expiration: 3600000